### ISSUE TITLE
jetpack compose samples

### ISSUE THREAD

**Issue by ismai117** [what3words/w3w-android-components#24]
Hi, is there any what3words ui samples for jetpack compose?

I'm trying to convert lat/long into 3 words and show it on google Maps

**Comment by mani-w3w** [comment]
Hi @ismai117, we are working to make our android autosuggest component to work inside of a Composable, aiming for the end of the Q4 release.

But your use case seems like you might not need our **text autosuggest component** but our **map component** instead, there are tutorials and sample apps on this GitHub repo that will allow you to convert a lat/long into what3words address and show it on a new or existing GoogleMaps. 

Here is the repo: https://github.com/what3words/w3w-android-map-components - hopefully, this helps you with your use case until we add support for jetpack compose to our text autosuggest component.

**Comment by ismai117** [comment]
Hi, yes I just need the map component, but im struggling to implement it with jetpack compose using AndroidView, do you know if there's any samples which implement a map component with compose?

**Comment by mani-w3w** [comment]
Hi @ismai117, apologies for the delay, but we were making sure that we had enough samples of how to use the map component with Jetpack compose, please find samples here: https://github.com/what3words/w3w-android-map-components/tree/main/google-maps-compose-sample. 

Any questions you might have, please let me know. 

Best regards,
Mani

**Comment by ismai117** [comment]
Hi Emanuel, 

No worries!, thanks for the samples

**Comment by ismai117** [comment]
Hi Emanuel, can developers build libraries on top of this for jetpack compose projects or can I contribute to this project?

**Comment by mani-w3w** [comment]
Hi @ismai117, apologies for not replying to this, yes, you can fork and make the changes you might need, if you have any contributions, please feel free to open a PR, and we will review it internally.

Will close this issue for now since the samples for jetpack compose are now available.

Thanks,
Mani
